WARNING  celery.redirected:log.py:227 token
WARNING  celery.redirected:log.py:227 **************************************************
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 ERROR    root:mylogger.py:84 测试结果:{'errorCode': 0, 'data': {'token': '096c39c0-7ff0-491f-9305-38c4d745c1a3', 'sid': '8TABNRoi7ROB'}}
ERROR    root:mylogger.py:84 测试结果:{'errorCode': 0, 'data': {'token': '096c39c0-7ff0-491f-9305-38c4d745c1a3', 'sid': '8TABNRoi7ROB'}}
WARNING  celery.redirected:log.py:227 [2021-05-22 15:48:54,324] | mylogger.py |ERROR : 测试结果:{'errorCode': 0, 'data': {'token': '096c39c0-7ff0-491f-9305-38c4d745c1a3', 'sid': '8TABNRoi7ROB'}}
WARNING  celery.redirected:log.py:227 **************************************************
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 DEBUG    root:mylogger.py:80 token:096c39c0-7ff0-491f-9305-38c4d745c1a3
DEBUG    root:mylogger.py:80 token:096c39c0-7ff0-491f-9305-38c4d745c1a3
WARNING  celery.redirected:log.py:227 [2021-05-22 15:48:54,325] | mylogger.py |DEBUG : token:096c39c0-7ff0-491f-9305-38c4d745c1a3
WARNING  celery.redirected:log.py:227 ^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 INFO     root:mylogger.py:78 case用例:合作伙伴信息1
INFO     root:mylogger.py:78 case用例:合作伙伴信息1
WARNING  celery.redirected:log.py:227 [2021-05-22 15:48:54,328] | mylogger.py |INFO  : case用例:合作伙伴信息1
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 INFO     root:mylogger.py:78 地址url：https://test.xlvren.com/bp/selectPartner
INFO     root:mylogger.py:78 地址url：https://test.xlvren.com/bp/selectPartner
WARNING  celery.redirected:log.py:227 [2021-05-22 15:48:54,329] | mylogger.py |INFO  : 地址url：https://test.xlvren.com/bp/selectPartner
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 INFO     root:mylogger.py:78 token：096c39c0-7ff0-491f-9305-38c4d745c1a3
INFO     root:mylogger.py:78 token：096c39c0-7ff0-491f-9305-38c4d745c1a3
WARNING  celery.redirected:log.py:227 [2021-05-22 15:48:54,330] | mylogger.py |INFO  : token：096c39c0-7ff0-491f-9305-38c4d745c1a3
WARNING  celery.redirected:log.py:227 header :{'Authorization': 'Bearer 096c39c0-7ff0-491f-9305-38c4d745c1a3', 'Content-Type': 'application/json'}
WARNING  celery.redirected:log.py:227 method :post
WARNING  celery.redirected:log.py:227 pararm :{"id":"12104","type":0}
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 DEBUG    root:mylogger.py:80 post 请求...
DEBUG    root:mylogger.py:80 post 请求...
WARNING  celery.redirected:log.py:227 [2021-05-22 15:48:54,332] | mylogger.py |DEBUG : post 请求...
WARNING  celery.redirected:log.py:227 DEBUG    urllib3.connectionpool:connectionpool.py:975 Starting new HTTPS connection (1): test.xlvren.com:443
DEBUG    urllib3.connectionpool:connectionpool.py:975 Starting new HTTPS connection (1): test.xlvren.com:443
WARNING  celery.redirected:log.py:227 DEBUG    urllib3.connectionpool:connectionpool.py:461 https://test.xlvren.com:443 "POST /bp/selectPartner HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:461 https://test.xlvren.com:443 "POST /bp/selectPartner HTTP/1.1" 200 None
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 DEBUG    root:mylogger.py:80 `````````````````````````````````````````````````
DEBUG    root:mylogger.py:80 `````````````````````````````````````````````````
WARNING  celery.redirected:log.py:227 [2021-05-22 15:48:54,523] | mylogger.py |DEBUG : `````````````````````````````````````````````````
WARNING  celery.redirected:log.py:227 post 请求 结束。。。。。