WARNING  celery.redirected:log.py:227 ^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 INFO     root:mylogger.py:78 case用例:客诉工单列表,当前责任是本人-已关闭
INFO     root:mylogger.py:78 case用例:客诉工单列表,当前责任是本人-已关闭
WARNING  celery.redirected:log.py:227 [2021-06-07 09:24:46,305] | mylogger.py |INFO  : case用例:客诉工单列表,当前责任是本人-已关闭
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 INFO     root:mylogger.py:78 地址url：https://test.xlvren.com/bp/workOrderList
INFO     root:mylogger.py:78 地址url：https://test.xlvren.com/bp/workOrderList
WARNING  celery.redirected:log.py:227 [2021-06-07 09:24:46,306] | mylogger.py |INFO  : 地址url：https://test.xlvren.com/bp/workOrderList
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 INFO     root:mylogger.py:78 token：b1b2c579-99ac-4557-95d3-246e825593e0
INFO     root:mylogger.py:78 token：b1b2c579-99ac-4557-95d3-246e825593e0
WARNING  celery.redirected:log.py:227 [2021-06-07 09:24:46,307] | mylogger.py |INFO  : token：b1b2c579-99ac-4557-95d3-246e825593e0
WARNING  celery.redirected:log.py:227 header :{'Authorization': 'Bearer b1b2c579-99ac-4557-95d3-246e825593e0', 'Content-Type': 'application/json'}
WARNING  celery.redirected:log.py:227 method :get
WARNING  celery.redirected:log.py:227 pararm :{"page":1,"size":2,"status":2}
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 DEBUG    root:mylogger.py:80 get 请求 ....
DEBUG    root:mylogger.py:80 get 请求 ....
WARNING  celery.redirected:log.py:227 [2021-06-07 09:24:46,308] | mylogger.py |DEBUG : get 请求 ....
WARNING  celery.redirected:log.py:227 DEBUG    urllib3.connectionpool:connectionpool.py:975 Starting new HTTPS connection (1): test.xlvren.com:443
DEBUG    urllib3.connectionpool:connectionpool.py:975 Starting new HTTPS connection (1): test.xlvren.com:443
WARNING  celery.redirected:log.py:227 DEBUG    urllib3.connectionpool:connectionpool.py:461 https://test.xlvren.com:443 "GET /bp/workOrderList?page=1&size=2&status=2 HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:461 https://test.xlvren.com:443 "GET /bp/workOrderList?page=1&size=2&status=2 HTTP/1.1" 200 None
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 DEBUG    root:mylogger.py:80 测试结果:get,,,{'errorCode': 0, 'data': [{'id': 1, 'type': 1, 'stationId': 100212, 'details': '12123123123', 'phone': '', 'status': 2, 'createTime': '2021-05-12 15:35:06', 'createUser': 304851520, 'currentUser': 62, 'createUserName': '志雄BP', 'stationName': '老虎岭', 'latestOperator': '志雄BP'}, {'id': 6, 'type': 1, 'stationId': 100213, 'details': '测试', 'phone': '', 'status': 2, 'createTime': '2021-05-12 15:44:03', 'createUser': 304851520, 'createUserName': '志雄BP', 'stationName': 'zx-test-617695', 'latestOperator': '穆鹏飞'}]}
DEBUG    root:mylogger.py:80 测试结果:get,,,{'errorCode': 0, 'data': [{'id': 1, 'type': 1, 'stationId': 100212, 'details': '12123123123', 'phone': '', 'status': 2, 'createTime': '2021-05-12 15:35:06', 'createUser': 304851520, 'currentUser': 62, 'createUserName': '志雄BP', 'stationName': '老虎岭', 'latestOperator': '志雄BP'}, {'id': 6, 'type': 1, 'stationId': 100213, 'details': '测试', 'phone': '', 'status': 2, 'createTime': '2021-05-12 15:44:03', 'createUser': 304851520, 'createUserName': '志雄BP', 'stationName': 'zx-test-617695', 'latestOperator': '穆鹏飞'}]}
WARNING  celery.redirected:log.py:227 [2021-06-07 09:24:46,477] | mylogger.py |DEBUG : 测试结果:get,,,{'errorCode': 0, 'data': [{'id': 1, 'type': 1, 'stationId': 100212, 'details': '12123123123', 'phone': '', 'status': 2, 'createTime': '2021-05-12 15:35:06', 'createUser': 304851520, 'currentUser': 62, 'createUserName': '志雄BP', 'stationName': '老虎岭', 'latestOperator': '志雄BP'}, {'id': 6, 'type': 1, 'stationId': 100213, 'details': '测试', 'phone': '', 'status': 2, 'createTime': '2021-05-12 15:44:03', 'createUser': 304851520, 'createUserName': '志雄BP', 'stationName': 'zx-test-617695', 'latestOperator': '穆鹏飞'}]}
WARNING  celery.redirected:log.py:227 get 请求结束。。。。。。