WARNING  celery.redirected:log.py:227 ---------------token---------------------
WARNING  celery.redirected:log.py:227 <configparser.ConfigParser object at 0x7f409043a208>
WARNING  celery.redirected:log.py:227 ---------------token---------------------
WARNING  celery.redirected:log.py:227 DEBUG    urllib3.connectionpool:connectionpool.py:975 Starting new HTTPS connection (1): test.xlvren.com:443
DEBUG    urllib3.connectionpool:connectionpool.py:975 Starting new HTTPS connection (1): test.xlvren.com:443
WARNING  celery.redirected:log.py:227 DEBUG    urllib3.connectionpool:connectionpool.py:461 https://test.xlvren.com:443 "POST /bp/login HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:461 https://test.xlvren.com:443 "POST /bp/login HTTP/1.1" 200 None
WARNING  celery.redirected:log.py:227 **************************************************
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 ERROR    root:mylogger.py:84 测试结果:{'errorCode': 0, 'data': {'token': '981a8c13-8daf-4d68-8c08-cc4f8468bff8'}}
ERROR    root:mylogger.py:84 测试结果:{'errorCode': 0, 'data': {'token': '981a8c13-8daf-4d68-8c08-cc4f8468bff8'}}
WARNING  celery.redirected:log.py:227 [2021-05-31 18:49:36,195] | mylogger.py |ERROR : 测试结果:{'errorCode': 0, 'data': {'token': '981a8c13-8daf-4d68-8c08-cc4f8468bff8'}}
WARNING  celery.redirected:log.py:227 **************************************************
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 DEBUG    root:mylogger.py:80 token:981a8c13-8daf-4d68-8c08-cc4f8468bff8
DEBUG    root:mylogger.py:80 token:981a8c13-8daf-4d68-8c08-cc4f8468bff8
WARNING  celery.redirected:log.py:227 [2021-05-31 18:49:36,196] | mylogger.py |DEBUG : token:981a8c13-8daf-4d68-8c08-cc4f8468bff8
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 DEBUG    root:mylogger.py:80 token:981a8c13-8daf-4d68-8c08-cc4f8468bff8
DEBUG    root:mylogger.py:80 token:981a8c13-8daf-4d68-8c08-cc4f8468bff8
WARNING  celery.redirected:log.py:227 [2021-05-31 18:49:36,198] | mylogger.py |DEBUG : token:981a8c13-8daf-4d68-8c08-cc4f8468bff8