WARNING  celery.redirected:log.py:227 ^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 INFO     root:mylogger.py:78 case用例:修改银行卡信息
INFO     root:mylogger.py:78 case用例:修改银行卡信息
WARNING  celery.redirected:log.py:227 [2021-05-31 18:51:12,958] | mylogger.py |INFO  : case用例:修改银行卡信息
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 INFO     root:mylogger.py:78 地址url：https://test.xlvren.com/bp/modifyBankInfo
INFO     root:mylogger.py:78 地址url：https://test.xlvren.com/bp/modifyBankInfo
WARNING  celery.redirected:log.py:227 [2021-05-31 18:51:12,959] | mylogger.py |INFO  : 地址url：https://test.xlvren.com/bp/modifyBankInfo
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 INFO     root:mylogger.py:78 token：066fe6e0-3ef4-4c42-a950-060c121abe2c
INFO     root:mylogger.py:78 token：066fe6e0-3ef4-4c42-a950-060c121abe2c
WARNING  celery.redirected:log.py:227 [2021-05-31 18:51:12,960] | mylogger.py |INFO  : token：066fe6e0-3ef4-4c42-a950-060c121abe2c
WARNING  celery.redirected:log.py:227 header :{'Authorization': 'Bearer 066fe6e0-3ef4-4c42-a950-060c121abe2c', 'Content-Type': 'application/json'}
WARNING  celery.redirected:log.py:227 method :post
WARNING  celery.redirected:log.py:227 pararm :{
 "bank": "中国银行",
 "bankAccount": "6217562000015065356",
 "bankUserName": "何军旺"
}
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 DEBUG    root:mylogger.py:80 post 请求...
DEBUG    root:mylogger.py:80 post 请求...
WARNING  celery.redirected:log.py:227 [2021-05-31 18:51:12,962] | mylogger.py |DEBUG : post 请求...
WARNING  celery.redirected:log.py:227 DEBUG    urllib3.connectionpool:connectionpool.py:975 Starting new HTTPS connection (1): test.xlvren.com:443
DEBUG    urllib3.connectionpool:connectionpool.py:975 Starting new HTTPS connection (1): test.xlvren.com:443
WARNING  celery.redirected:log.py:227 DEBUG    urllib3.connectionpool:connectionpool.py:461 https://test.xlvren.com:443 "POST /bp/modifyBankInfo HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:461 https://test.xlvren.com:443 "POST /bp/modifyBankInfo HTTP/1.1" 200 None
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 DEBUG    root:mylogger.py:80 `````````````````````````````````````````````````
DEBUG    root:mylogger.py:80 `````````````````````````````````````````````````
WARNING  celery.redirected:log.py:227 [2021-05-31 18:51:13,119] | mylogger.py |DEBUG : `````````````````````````````````````````````````
WARNING  celery.redirected:log.py:227 post 请求 结束。。。。。