WARNING  celery.redirected:log.py:227 ^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 INFO     root:mylogger.py:78 case用例:合作伙伴信息1
INFO     root:mylogger.py:78 case用例:合作伙伴信息1
WARNING  celery.redirected:log.py:227 [2021-05-24 16:46:59,405] | mylogger.py |INFO  : case用例:合作伙伴信息1
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 INFO     root:mylogger.py:78 地址url：https://test.xlvren.com/bp/selectPartner
INFO     root:mylogger.py:78 地址url：https://test.xlvren.com/bp/selectPartner
WARNING  celery.redirected:log.py:227 [2021-05-24 16:46:59,406] | mylogger.py |INFO  : 地址url：https://test.xlvren.com/bp/selectPartner
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 INFO     root:mylogger.py:78 token：f32ccaf7-d72c-437a-915e-64f57ce25195
INFO     root:mylogger.py:78 token：f32ccaf7-d72c-437a-915e-64f57ce25195
WARNING  celery.redirected:log.py:227 [2021-05-24 16:46:59,407] | mylogger.py |INFO  : token：f32ccaf7-d72c-437a-915e-64f57ce25195
WARNING  celery.redirected:log.py:227 header :{'Authorization': 'Bearer f32ccaf7-d72c-437a-915e-64f57ce25195', 'Content-Type': 'application/json'}
WARNING  celery.redirected:log.py:227 method :post
WARNING  celery.redirected:log.py:227 pararm :{"id":"12104","type":0}
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 DEBUG    root:mylogger.py:80 post 请求...
DEBUG    root:mylogger.py:80 post 请求...
WARNING  celery.redirected:log.py:227 [2021-05-24 16:46:59,408] | mylogger.py |DEBUG : post 请求...
WARNING  celery.redirected:log.py:227 DEBUG    urllib3.connectionpool:connectionpool.py:975 Starting new HTTPS connection (1): test.xlvren.com:443
DEBUG    urllib3.connectionpool:connectionpool.py:975 Starting new HTTPS connection (1): test.xlvren.com:443
WARNING  celery.redirected:log.py:227 DEBUG    urllib3.connectionpool:connectionpool.py:461 https://test.xlvren.com:443 "POST /bp/selectPartner HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:461 https://test.xlvren.com:443 "POST /bp/selectPartner HTTP/1.1" 200 None
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 DEBUG    root:mylogger.py:80 `````````````````````````````````````````````````
DEBUG    root:mylogger.py:80 `````````````````````````````````````````````````
WARNING  celery.redirected:log.py:227 [2021-05-24 16:46:59,660] | mylogger.py |DEBUG : `````````````````````````````````````````````````
WARNING  celery.redirected:log.py:227 post 请求 结束。。。。。